### ISSUE TITLE
Not working with requirejs 2.2.0

### ISSUE THREAD

**Issue by fabslab** [requirejs/xrayquire#15]
Uncaught TypeError: Cannot read property 'prototype' of undefined
at `modProto = context.Module.prototype,`

**Comment by jrburke** [comment]
I just tried it with 2.3.0, confirmed in this commit: https://github.com/requirejs/xrayquire/commit/ca32cdec501542fe48cfd13a9a08a8f3709822da and it seems to work with that version, so closing this.

Tried it latest shipping versions of Chrome, Firefox and Safari.
